// Generated by CoffeeScript 1.4.0
(function() {

  module.exports = {
    ifttt: {
      user: 'admin',
      password: '1234'
    },
    mongodb: {
      url: 'mongodb://localhost/pickpocket'
    },
    server: [3000]
  };

}).call(this);
