// Generated by CoffeeScript 1.4.0
(function() {
  var api, express, posts;

  express = require('express');

  api = require('./middleware/api');

  posts = require('./routes/posts');

  module.exports = function(config) {
    var app;
    app = express();
    app.configure(function() {
      require('mongoose').connect(config.mongodb.url);
      app.engine('jade', require('jade').__express);
      app.set('view engine', 'jade');
      return app.set('views', __dirname + '/views');
    });
    app.use(api(config.ifttt));
    app.use(express["static"]('public'));
    app.get('/', posts.index);
    return app;
  };

}).call(this);
