// Generated by CoffeeScript 1.4.0
(function() {
  var Post;

  Post = require('../models/post');

  module.exports.index = function(req, res) {
    return Post.find().sort('-created').exec(function(err, posts) {
      return res.render('posts-index', {
        posts: posts
      });
    });
  };

}).call(this);
